{% set name = "llama" %}
{% set version = "1.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/antonmedv/llama/archive/v{{ version }}.tar.gz
  sha256: e28e48ec88de76be2b21fffa81ced159d78b9fd0b5e8abe0e19cbff086bf26d4

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  requires:
    - m2-grep  # [win]
  commands:
    - 'llama --help 2>&1 | grep -q "Usage: walk"'

about:
  home: https://github.com/antonmedv/llama
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Terminal file manager
  dev_url: https://github.com/antonmedv/llama

extra:
  recipe-maintainers:
    - danielnachun
