{% set name = "llama" %}
{% set version = "1.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/antonmedv/llama/archive/v{{ version }}.tar.gz
  sha256: 76e8db66942af53447f5ab3f0aaec49b539a68714130e46c83a01fff9c00438f

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  requires:
    - m2-grep  # [win]
  commands:
    - 'llama --help 2>&1 | grep -q "Usage: walk"'

about:
  home: https://github.com/antonmedv/llama
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Terminal file manager
  dev_url: https://github.com/antonmedv/llama

extra:
  recipe-maintainers:
    - danielnachun
